development:
  secret_token: "my_secret_token"
  secret_key_base: "abcdef0123456789"

test:
  secret_key_base:  asdflkhasgdslhafddsdlflakhsdf

production:
  secret_key_base: 523saa5h2jlj6nlk4sddn6lk4
